name: publish

on:
  release:
    types: [created]

jobs:
  publish-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Setup Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - --version 1.1.15
          export PATH=$HOME/.local/bin:${PATH}
      - name: Install Dependencies
        run: export PATH=$HOME/.local/bin:${PATH} && poetry install
      - name: Build
        run: export PATH=$HOME/.local/bin:${PATH} && poetry build
      - name: Publish
        run: export PATH=$HOME/.local/bin:${PATH} && poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}